---
abstract: 'Build an RPM from your Dist::Zilla release'
author:
  - 'Vincent Lequertier <sky@riseup.net>'
build_requires:
  File::Which: 0
  Test::DZil: 0
  Test::Differences: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-RPM
requires:
  Carp: 0
  Dist::Zilla: 0
  Dist::Zilla::App: 0
  File::Temp: 0
  Moose: 0
  Moose::Autobox: 0
  Path::Class: 0
  Text::Template: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Zilla-Plugin-RPM
  repository: git://github.com/SkySymbol/perl-dist-zilla-plugin-rpm.git
version: 0.007
